export const ADD_SAVED_ATTRACTION = 'ADD_SAVED_ATTRACTION';
export const DELETE_SAVED_ATTRACTION = 'DELETE_SAVED_ATTRACTION';
export const FETCH_DISCOVERY = 'FETCH_DISCOVERY';
export const FETCH_CURRENT_LOCATION = 'FETCH_CURRENT_LOCATION';
